spring:
    application:
      name: rest-with-java-spring
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rest-with-java-spring?useTimezone=true&serverTimezone=UTC
      username: root
      password: asdf
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
      show-sql: false
      open-in-view: false
logging:
  level:
    root: warn
    _xSchneider:
      com:
        github:
          rest_with_java_spring: warn

